/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current authenticated account and its role-specific profile ids */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publishers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a publisher organization (RegisterForm.tsx role=publisher) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreatePublisherRequest"];
                };
            };
            responses: {
                /** @description Created, verificationStatus=unverified */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Publisher"];
                    };
                };
                /** @description Validation failure */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publishers/{publisherId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public publisher profile (PublisherProfileCard.tsx) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    publisherId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Publisher"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publishers/{publisherId}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregate counts for the publisher dashboard (AnalyticsCards.tsx) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    publisherId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublisherAnalytics"];
                    };
                };
                /** @description Not a member of this publisher */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publishers/{publisherId}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent activity feed (RecentActivity.tsx) */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    publisherId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["ActivityEvent"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publishers/{publisherId}/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This publisher's articles, current version only (MyArticlesTable.tsx) */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    publisherId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["ArticleVersionSummary"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publishers/{publisherId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reviews and disputes against this publisher's articles (ReviewsDisputes.tsx) */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    publisherId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: (components["schemas"]["Review"] | components["schemas"]["Dispute"])[];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publishers/{publisherId}/credibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Published credibility breakdown (CredibilityPanel.tsx) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    publisherId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CredibilityBreakdown"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publishers/{publisherId}/credibility-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Credibility score trend (CredibilityPanel.tsx:84 sparkline) */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    publisherId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["CredibilityHistoryPoint"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publishers/pending-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Publisher verification queue (resolves OPEN_QUESTIONS.md #8) */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK, admin only */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Publisher"][];
                            nextCursor: string | null;
                        };
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publishers/{publisherId}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve or reject a publisher's verification (resolves OPEN_QUESTIONS.md #6a, #8) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    publisherId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["VerifyPublisherRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Publisher"];
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviewers/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply to become a reviewer (RegisterForm.tsx role=reviewer) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ApplyAsReviewerRequest"];
                };
            };
            responses: {
                /** @description Created, approvalStatus=pending */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reviewer"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviewers/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reviewer approval queue (resolves OPEN_QUESTIONS.md #8) */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK, admin only */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Reviewer"][];
                            nextCursor: string | null;
                        };
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviewers/{reviewerId}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve or reject a reviewer application */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reviewerId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ReviewerDecisionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Reviewer"];
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an article and its v1.0 version (PublishArticlePanel.tsx) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateArticleRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateArticleResponse"];
                    };
                };
                /** @description Not a member of the target publisher, or publisher not verified */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{articleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Article + its current version (public, unauthenticated) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    articleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Article"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{articleId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full version history — public and unauthenticated like verification itself (resolves OPEN_QUESTIONS.md #12) */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    articleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["ArticleVersion"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Submit a correction/update as a new version */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    articleId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateArticleVersionRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArticleVersion"];
                    };
                };
                /** @description Not a member of the owning publisher */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{articleId}/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One version's full detail, for diffing against another (ArticleEditHistory.tsx) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    articleId: string;
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArticleVersion"];
                    };
                };
                /** @description Not found, or redacted (see GET /versions/{versionId}/redaction) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Hard-delete a draft version — draft only (resolves OPEN_QUESTIONS.md #9) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    articleId: string;
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Version is no longer a draft */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Edit a draft version's content — draft only; append-only once submitted (resolves OPEN_QUESTIONS.md #9) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    articleId: string;
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateArticleVersionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArticleVersion"];
                    };
                };
                /** @description Version is no longer a draft */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/articles/{articleId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive an article at any lifecycle stage (resolves OPEN_QUESTIONS.md #9) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    articleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Article"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{articleId}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The core verification endpoint — public, unauthenticated, must never be slow or down (build prompt, Scale) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    articleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VerificationResult"];
                    };
                };
                /** @description Not registered — trustStatus is always 'notfound' here, never absent */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NotFoundVerificationResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{versionId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence attached to this version (EvidenceSection.tsx) */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Evidence"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Attach evidence to a draft version (MediaEvidenceUpload.tsx) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UploadEvidenceRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Evidence"];
                    };
                };
                /** @description Version is no longer a draft — evidence binds at submission and is then append-only */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{versionId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reviews attached to this version (ReviewerNotes.tsx) */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Review"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Attach a review — 403 if the reviewer is structurally affiliated with the publisher (resolves OPEN_QUESTIONS.md #4) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateReviewRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Review"];
                    };
                };
                /** @description Reviewer is affiliated with this publisher, or not an approved reviewer */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{reviewId}/retract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retract own review — original text stays visible and intact (build prompt invariant) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reviewId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RetractReviewRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Review"];
                    };
                };
                /** @description Not the reviewer who wrote it */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{versionId}/disputes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disputes filed against this version — always visible, never suppressible (build prompt invariant) */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Dispute"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        /** File a dispute (resolves OPEN_QUESTIONS.md #2) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["FileDisputeRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dispute"];
                    };
                };
                /** @description Reviewer is affiliated with this publisher, or not an approved reviewer */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/disputes/{disputeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One dispute with its full event history */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    disputeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dispute"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/disputes/{disputeId}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publisher response: free text, a correction (new ArticleVersion), or both — never deletion or suppression (resolves OPEN_QUESTIONS.md #2) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    disputeId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RespondToDisputeRequest"];
                };
            };
            responses: {
                /** @description Event appended */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dispute"];
                    };
                };
                /** @description Not a member of the disputed publisher */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/disputes/{disputeId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Filer withdraws, or filer/admin marks resolved — never the publisher; SourceIt does not adjudicate truth, so this is procedural, not a verdict (build prompt invariant) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    disputeId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ResolveDisputeRequest"];
                };
            };
            responses: {
                /** @description Event appended */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dispute"];
                    };
                };
                /** @description Not the filer and not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{versionId}/redaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The tombstone for this version, if redacted — public (resolves OPEN_QUESTIONS.md #5) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redacted — tombstone follows */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Redaction"] & Record<string, never>;
                    };
                };
                /** @description Not redacted */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Redact a version under legal takedown — admin only, redaction not deletion (build prompt invariant) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateRedactionRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Redaction"] & Record<string, never>;
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/versions/{versionId}/anchor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The anchor state for this version — always present, always one of pending/anchored/anchor_failed (resolves OPEN_QUESTIONS.md #1) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnchorRecord"];
                    };
                };
                /** @description Version does not exist or is still a draft (no anchor record yet) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved-articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current reader's saved articles (SavedArticles.tsx) */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["SavedArticle"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Bookmark an article */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateSavedArticleRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SavedArticle"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved-articles/{savedArticleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unbookmark — never affects the underlying article */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    savedArticleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not the owning reader */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisher-follows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current reader's followed publishers (TrustedPublishers.tsx) */
        get: {
            parameters: {
                query?: {
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["PublisherFollow"][];
                            nextCursor: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Follow a publisher */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreatePublisherFollowRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PublisherFollow"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisher-follows/{followId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unfollow a publisher */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    followId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not the owning reader */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            id: string;
            /** Format: email */
            email: string;
            fullName: string;
            /** @enum {string} */
            role: "reader" | "publisher" | "reviewer" | "admin";
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            createdAt: string;
        };
        MeResponse: {
            account: components["schemas"]["Account"];
            publisherIds: string[];
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            reviewerId: string | null;
        };
        Error: {
            code: string;
            message: string;
            details?: {
                field: string;
                message: string;
            }[];
        };
        Publisher: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            id: string;
            organizationName: string;
            displayName: string;
            /** Format: uri */
            website: string;
            description: string;
            categories: string[] | null;
            /** @enum {string} */
            verificationStatus: "unverified" | "pending" | "verified" | "rejected";
            transparencyLevel: number;
            credibilityScore: number;
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            createdAt: string;
        };
        CreatePublisherRequest: {
            organizationName: string;
            /** Format: uri */
            website: string;
            description: string;
        };
        PublisherAnalytics: {
            totalArticlesPublished: number;
            verifiedArticleCount: number;
            pendingReviewCount: number;
            disputedArticleCount: number;
        };
        ActivityEvent: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            id: string;
            /** @enum {string} */
            type: "publish" | "blockchain" | "review" | "update" | "correction" | "dispute_filed" | "redaction";
            title: string;
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            articleId: string | null;
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            createdAt: string;
        };
        ArticleVersionSummary: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            articleId: string;
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            id: string;
            /** @enum {string} */
            category: "politics" | "technology" | "health" | "science" | "business";
            versionLabel: string;
            headline: string;
            /** @enum {string} */
            reviewStatus: "draft" | "pending_review" | "verified";
            /** @enum {string|null} */
            anchorStatus: "pending" | "anchored" | "anchor_failed" | null;
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            publishedAt: string | null;
        };
        ReviewerPublic: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            id: string;
            displayName: string;
            title: string | null;
        };
        Review: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            id: string;
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            articleVersionId: string;
            reviewer: components["schemas"]["ReviewerPublic"];
            /** @enum {string} */
            type: "confirmation" | "clarification" | "correction_note";
            comment: string;
            isRetracted: boolean;
            retractedReason: string | null;
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            createdAt: string;
        };
        DisputeEvent: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            id: string;
            /** @enum {string} */
            eventType: "publisher_responded" | "withdrawn" | "resolved_corrected" | "resolved_addressed_no_verdict";
            note: string | null;
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            correctionVersionId: string | null;
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            createdAt: string;
        };
        Dispute: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            id: string;
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            articleVersionId: string;
            filedBy: components["schemas"]["ReviewerPublic"];
            reason: string;
            /** @enum {string} */
            status: "open" | "publisher_responded" | "withdrawn" | "resolved_corrected" | "resolved_addressed_no_verdict";
            events: components["schemas"]["DisputeEvent"][];
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            createdAt: string;
        };
        CredibilityBreakdown: {
            score: number;
            tier: string;
            trend: number | null;
            factors: {
                verifiedArticles: number;
                disputedClaims: number;
                transparentCorrections: number;
            };
        };
        CredibilityHistoryPoint: {
            score: number;
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            recordedAt: string;
        };
        VerifyPublisherRequest: {
            /** @enum {string} */
            decision: "verified" | "rejected";
        };
        Reviewer: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            id: string;
            affiliation: string;
            expertise: string;
            title: string | null;
            pseudonym: string | null;
            useLegalName: boolean;
            /** @enum {string} */
            approvalStatus: "pending" | "approved" | "rejected";
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            createdAt: string;
        };
        ApplyAsReviewerRequest: {
            affiliation: string;
            expertise: string;
            applicationReason: string;
        };
        ReviewerDecisionRequest: {
            /** @enum {string} */
            decision: "approved" | "rejected";
        };
        Article: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            id: string;
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            publisherId: string;
            /** @enum {string} */
            category: "politics" | "technology" | "health" | "science" | "business";
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            createdAt: string;
        };
        ArticleVersion: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            id: string;
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            articleId: string;
            versionMajor: number;
            versionMinor: number;
            /** @example v1.0 */
            versionLabel: string;
            headline: string;
            summary: string;
            content: string;
            authorName: string;
            tags: string[] | null;
            sourceLinks: string[] | null;
            /** @enum {string} */
            changeType: "original_published" | "major_update" | "minor_correction";
            changeSummary: string | null;
            /** @enum {string} */
            reviewStatus: "draft" | "pending_review" | "verified";
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            previousVersionId: string | null;
            contentHash: string | null;
            previousHash: string | null;
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            publishedAt: string | null;
        };
        CreateArticleResponse: {
            article: components["schemas"]["Article"];
            version: components["schemas"]["ArticleVersion"];
        };
        CreateArticleRequest: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            publisherId: string;
            /** @enum {string} */
            category: "politics" | "technology" | "health" | "science" | "business";
            headline: string;
            summary: string;
            content: string;
            authorName: string;
            tags?: string[];
            sourceLinks?: string[];
            /** @default false */
            submit: boolean;
        };
        CreateArticleVersionRequest: {
            headline: string;
            summary: string;
            content: string;
            authorName: string;
            tags?: string[];
            sourceLinks?: string[];
            /** @enum {string} */
            changeType: "original_published" | "major_update" | "minor_correction";
            changeSummary?: string;
            /** @default false */
            submit: boolean;
        };
        Evidence: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            id: string;
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            articleVersionId: string;
            /** @enum {string} */
            fileType: "image" | "video" | "document";
            /** @enum {string} */
            tag: "cover_image" | "media" | "evidence" | "source";
            filename: string;
            caption: string | null;
            contentHash: string;
            /** Format: uri */
            sourceUrl: string | null;
            isArchivedSnapshot: boolean;
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            createdAt: string;
        };
        AnchorRecord: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            articleVersionId: string;
            /** @enum {string} */
            status: "pending" | "anchored" | "anchor_failed";
            leafHash: string;
            merkleProof: string[] | null;
            blockHeight: number | null;
            chainConfirmations: number;
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            anchoredAt: string | null;
        };
        Redaction: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            articleVersionId: string;
            /** @enum {string} */
            category: "court_order" | "defamation_ruling" | "right_to_erasure";
            tombstoneHash: string;
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            redactedAt: string;
        } | null;
        TrustSummaryFacts: {
            registryMember: boolean;
            versionMatch: boolean;
            publisherVerified: boolean;
            evidenceCount: number;
            openDisputeCount: number;
        };
        VerificationResult: {
            article: components["schemas"]["Article"];
            currentVersion: components["schemas"]["ArticleVersion"];
            versionHistory: components["schemas"]["ArticleVersion"][];
            evidence: components["schemas"]["Evidence"][];
            reviews: components["schemas"]["Review"][];
            publisher: components["schemas"]["Publisher"];
            anchorRecord: components["schemas"]["AnchorRecord"];
            redaction: components["schemas"]["Redaction"];
            /** @enum {string} */
            trustStatus: "authentic" | "authentic_under_review" | "updated" | "disputed" | "publisher_unverified" | "notfound";
            trustSummary: components["schemas"]["TrustSummaryFacts"];
        };
        NotFoundVerificationResult: {
            /** @enum {string} */
            trustStatus: "notfound";
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            queriedId?: string;
        };
        UploadEvidenceRequest: {
            /** @enum {string} */
            fileType: "image" | "video" | "document";
            /** @enum {string} */
            tag: "cover_image" | "media" | "evidence" | "source";
            filename: string;
            caption?: string;
            /** Format: uri */
            sourceUrl?: string;
        };
        CreateReviewRequest: {
            /** @enum {string} */
            type: "confirmation" | "clarification" | "correction_note";
            comment: string;
        };
        RetractReviewRequest: {
            reason?: string;
        };
        FileDisputeRequest: {
            reason: string;
        };
        RespondToDisputeRequest: {
            note?: string;
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            correctionVersionId?: string;
        };
        ResolveDisputeRequest: {
            /** @enum {string} */
            eventType: "withdrawn" | "resolved_corrected" | "resolved_addressed_no_verdict";
            note?: string;
        };
        CreateRedactionRequest: {
            /** @enum {string} */
            category: "court_order" | "defamation_ruling" | "right_to_erasure";
            reason: string;
        };
        SavedArticle: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            id: string;
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            articleId: string;
            title: string;
            publisherName: string;
            /** @enum {string} */
            trustStatus: "authentic" | "authentic_under_review" | "updated" | "disputed" | "publisher_unverified" | "notfound";
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            savedAt: string;
        };
        CreateSavedArticleRequest: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            articleId: string;
        };
        PublisherFollow: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            id: string;
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            publisherId: string;
            publisherName: string;
            verified: boolean;
            credibilityScore: number;
            /**
             * Format: date-time
             * @example 2026-04-15T14:30:00Z
             */
            createdAt: string;
        };
        CreatePublisherFollowRequest: {
            /**
             * Format: uuid
             * @example b3f1c9a0-1e2d-4a3b-9c8f-6d5e4f3a2b1c
             */
            publisherId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
